dbt_streaming_demo:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: thriftserver
      port: 10000
      schema: default
      user: root
      connect_retries: 5
      connect_timeout: 10